---
title: "Spectral_Deconvolution"
author: "Ayudante de investigaciOn, Jefferson Pastuna"
date: "2024-06-09"
output:
  github_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
usethis::git_vaccinate()

```

### Introduction

Write an Introduction.

### Before to start

Write a package description.

### eRah package workflow

How to star.

```{r echo=TRUE, message=FALSE, warning=FALSE}

# eRah package installation
#install.packages('erah')
# eRah library call
library(erah)

```

Folder files

```{r echo=TRUE}

# Delete all file that are not in folders
unlink('Data/Data_to_eRah/*')
# Data folder path
createdt('Data/Data_to_eRah/')

```

New experiment.


```{r echo=TRUE}

instrumental <- read.csv('Data/Metadata_to_eRah/Metadata_inst.csv')
phenotype <- read.csv('Data/Metadata_to_eRah/Metadata_pheno.csv')

raw_data <- newExp(instrumental = instrumental,
                   phenotype = phenotype,
                   info = 'I. guayusa volatilome')

```

Compound deconvolution

Parameter

```{r echo=TRUE}

dec_par <- setDecPar(min.peak.width = 3,
                     min.peak.height = 500,
                     noise.threshold = 50,
                     avoid.processing.mz = c(50:69,73:75,147:149))

```

parallel processing

```{r echo=TRUE}

plan(future::multisession,
     workers = 14)

```

Deconvolution

```{r echo=TRUE, warning=FALSE}

dec_data <- deconvolveComp(raw_data,
                           dec_par)

```

Alignment

```{r echo=TRUE}

# Alignment parameters
alig_par <- setAlPar(min.spectra.cor = 0.9,
                     max.time.dist = 3,
                     mz.range = 50:500)
# Alignment
peak_alig <- alignComp(dec_data,
                       alParameters = alig_par)

```

Missing compound recovery

```{r echo=TRUE, warning=FALSE}

peak_find <- recMissComp(peak_alig,
                         min.samples = 3)

```

Identification

```{r echo=TRUE, warning=FALSE}

# Loading NIST 20 (*.msp) library
nist.database <- importMSP(filename = "E:/NIST_20_Library/Result/NIST20EI_2eRah.MSP",
                           DB.name = "NIST",
                           DB.version = "NIST20",
                           DB.info = "NIST MS Search Export")
# Save library for a posterior faster loading
save(nist.database, file= "E:/NIST_20_Library/Result/NIST20EI_2eRah.rda")
# Load R library
load("E:/NIST_20_Library/Result/NIST20EI_2eRah.rda")
mslib <- nist.database
# Identification
peak_iden <- identifyComp(peak_find,
                          id.database = mslib,
                          mz.range = NULL,
                          n.putative = 20)
# Identified compound
id_list <- idList(peak_iden)
# Exporting identified compounds
write.csv(id_list,
          file = "Result/eRah_Result/NIST_Identification.csv")

```

Mirror plot of identified compounds

```{r echo=TRUE}

plotSpectra(peak_iden, 1, 1, draw.color = "red")

```

Exporting spectra to NIST identification

```{r echo=TRUE}

export2MSP(peak_iden,
           store.path = "Result/eRah_Result",
           alg.version = 2)

```

